#ifndef ACTORSENUM_H
#define ACTORSENUM_H

enum ActorType
{
    //CONSTRUCTORS
    CONSTRUCTORS_START = 0,
    RAIL_CONSTRUCTOR,
    SIGNAL_CONSTRUCTOR,
    RAIL_SELECTOR,
    PORTAL_CONSTRUCTOR,
    CONSTRUCTORS_END = 99,
    //STATIC ACTORS
    STATIC_ACTORS_START = 100,
    STATIC_ACTORS_END = 199,
    //RAILWAY ACTORS
    RAILWAY_ACTORS_START = 200,
    RAIL_ACTOR,
    SIGNAL_ACTOR,
    PORTAL_ACTOR,
    RAILWAY_ACTORS_END = 299,
    //VEHICLE ACTORS
    VEHICLE_ACTORS_START = 300,
    VEHICLE_ACTORS_END = 399,
    //SELECTORS
    SELECTORS_START = 400,
    SELECTORS_END = 499,
};

#endif // ACTORSENUM_H
