#ifndef COLORSENUM_H
#define COLORSENUM_H


enum colors
{
    DEFAULT_COLOR,
    RED_BOLD_COLOR,
    BLUE_BOLD_COLOR,
    GREEN_BOLD_COLOR,
    BLACK_BOLD_COLOR,
    WHITE_BOLD_COLOR,
    YELLOW_BOLD_COLOR,
    RED_COLOR,
    BLUE_COLOR,
    GREEN_COLOR,
    BLACK_COLOR,
    WHITE_COLOR,
    YELLOW_COLOR
};

#endif // COLORSENUM_H
