#ifndef CONSOLEENUMS_H
#define CONSOLEENUMS_H


enum colors
{
    DEFAULT_COLOR,
    RED_BOLD_COLOR,
    BLUE_BOLD_COLOR,
    GREEN_BOLD_COLOR,
    BLACK_BOLD_COLOR,
    WHITE_BOLD_COLOR,
    YELLOW_BOLD_COLOR,
    RED_COLOR,
    BLUE_COLOR,
    GREEN_COLOR,
    BLACK_COLOR,
    WHITE_COLOR,
    YELLOW_COLOR
};

enum durationOfText //IN TICK TIME (30ms)
{
    INSTANT_DURATION = 10,
    SHORT_DURATION = 50,
    MIDDLE_DURATION = 150,
    LONG_DURATION = 400,
    VERY_LONG_DURATION = 800,

};

#endif // CONSOLEENUMS_H
