#ifndef MAINWINDOWENUM_H
#define MAINWINDOWENUM_H

enum OptionMode
{
    OPTION_MODE_START = 0,
    OPTION_MODE_END = 99,

    //EDIT+ADD
    EDIT_MODE_START = 100,
    EDIT_MODE_FREE,
    RAIL_ADD_MODE,
    SIGNAL_ADD_MODE,
    PORTAL_ADD_MODE,
    EDIT_ADD_END = 199,

    //EDIT+SELECT
    SELECT_EDIT_START = 200,
    RAIL_SELECTOR_MODE,
    EDIT_MODE_END = 299,

    //PLAY+ADD
    PLAY_MODE_START = 300,
    PLAY_MODE_FREE,
    ADD_PLAY_END = 399,

    //PLAY+SELECT
    SELECT_PLAY_START = 400,
    PLAY_MODE_END = 499,
};

enum ConstructorsEnum
{
    //CONSTRUCTORS
    RAIL_CONSTRUCTOR = 1,
    SIGNAL_CONSTRUCTOR,
    RAIL_SELECTOR,
    PORTAL_CONSTRUCTOR,
};


#endif // MAINWINDOWENUM_H
