#ifndef MAINWINDOWENUM_H
#define MAINWINDOWENUM_H

enum OptionMode
{
    OPTION_MODE_START = 0,
    OPTION_MODE_END = 99,

    //EDIT+ADD
    EDIT_MODE_START = 100,
    //constructors start
    RAIL_CONSTRUCT_MODE,
    SIGNAL_CONSTRUCT_MODE,
    PORTAL_CONSTRUCT_MODE,
    //constructors end
    EDIT_ADD_END = 199,

    //EDIT+SELECT
    EDIT_SELECT_START = 200,
    EDIT_SELECT_RAIL,
    EDIT_MODE_END = 299,

    //PLAY+ADD
    PLAY_MODE_START = 300,
    PLAY_ADD_TRAIN,
    PLAY_ADD_END = 399,

    //PLAY+SELECT
    PLAY_SELECT_START = 400,

    PLAY_SELECT_TRAIN,

        //TRAIN_MENU
        TRAIN_MODE_SELECT_PATH, //but1
        TRAIN_MODE_MOVE_TO,
        TRAIN_MODE_MOVIE_VIA,
        TRAIN_MODE_CHANGE_DIRECTION,
        TRAIN_MODE_CHANGE_MODE,
        TRAIN_MODE_UNCOUPLE,
        TRAIN_MODE_LOAD,
        TRAIN_MODE_UNLOAD,
        TRAIN_MODE_LEAVE_TRAIN,
        TRAIN_MODE_EXIT, //but24

    PLAY_MODE_END = 499,
};

#endif // MAINWINDOWENUM_H
