#ifndef MAINWINDOWENUM_H
#define MAINWINDOWENUM_H

enum OptionMode
{
    OPTION_MODE_START = 0,
    OPTION_MODE_END = 99,

    //EDIT+ADD
    EDIT_MODE_START = 100,
    EDIT_MODE_FREE,
    //constructors start
    RAIL_CONSTRUCT_MODE,
    SIGNAL_CONSTRUCT_MODE,
    PORTAL_CONSTRUCT_MODE,
    //constructors end
    EDIT_ADD_END = 199,

    //EDIT+SELECT
    EDIT_SELECT_START = 200,
    EDIT_SELECT_RAIL,
    EDIT_MODE_END = 299,

    //PLAY+ADD
    PLAY_MODE_START = 300,
    PLAY_MODE_FREE,
    PLAY_ADD_TRAIN,
    PLAY_ADD_END = 399,

    //PLAY+SELECT
    PLAY_SELECT_START = 400,
    PLAY_SELECT_TRAIN,
    PLAY_MODE_END = 499,
};

#endif // MAINWINDOWENUM_H
